server: 
  port: 80
  servlet: 
    encoding: 
      charset: utf-8
      force: true


spring: 
  mvc: 
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#  datasource:
#    url: jdbc:mysql://localhost:3306/bookhub?serverTimeZone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: asd1234   
#            
  datasource: # DB 설정
    url: jdbc:h2:mem:testdb;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: user # 유저 이름
    password: # 비밀번호 (비워두면 비밀번호 X)
  sql: 
    init: # 초기 sql 파일 읽기 
      schema-locations: # 스키마 (테이블 생성 등)
      - classpath:db/schema.sql 
      data-locations: # 샘플 데이터
      - classpath:db/data.sql
  h2: 
    console: 
      enabled: true
  output: 
    ansi: 
      enabled: always

mybatis: 
 mapper-locations:
  - classpath:mapper/**.xml
 configuration:
   map-underscore-to-camel-case: true 
   log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
   
logging:
  level:
    org.mybatis: DEBUG
    
    
    
pagination:
  size: 10
