server:
  port: 80
  servlet:
    encoding:
      charset: utf-8
      force: true

spring:
  mvc:
    view:
      prefix: /WEB-INF/view/
      suffix: .jsp
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

#  datasource:
#    url: jdbc:mysql://13.124.61.207:3306/bookhub?serverTimeZone=Asia/Seoul
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: root
#    password: zp426486!!ZP

  datasource:
    url: jdbc:mysql://54.180.81.23:3306/bookhub?serverTimeZone=Asia/Seoul
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: bookhub
    password: asd1234!

#  datasource: # DB 설정
#    url: jdbc:h2:~/spring-bookhub-db2;MODE=MySQL # Embedded Mode ->  H2 DB 데이터를 로컬에 직접 저장
#    driver-class-name: org.h2.Driver
#    username: user # 유저 이름
#    password: # 비밀번호 (비워두면 비밀번호 X)



  sql:
    init: # 초기 sql 파일 읽기
      mode: never #  always : 서버 실행시마다 data, schema 읽음, never : 읽지 않음
#      이부분은 gradle implementation h2 일때만 사용
#      schema-locations: # 스키마 (테이블 생성 등)
#        - classpath:schema.sql
#      data-locations: # 샘플 데이터
#        - classpath:data.sql
#  h2:
#    console:
#      enabled: true
#  output:
#    ansi:
#      enabled: always

  mail:
    host: smtp.gmail.com
    port: 587
    username: leeji34230@gmail.com
    password: ylwjzhfkwyadmwfr
    properties: 
      mail:
        smtp:
          auth: true #SMTP 서버에 인증 필요한 경우 true
          starttls: #SMTP 서버가 TLS를 사용하여 안전한 연결을 요구하는 경우 true
            enble: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
      auth-code-expiration-millis: 1800000  # 이메일 인증 코드 만료 시간 - 30분 설정

  impKey: "0841453800077355"
  impSecretKey: "ipQe2Y6MGOwusDOos8IG7KyICvl7bR6OSFNUveEOKgLTkAYQV02voGuJMLzDf2gYwZbBwFcVHCmAkYYf"

mybatis:
  mapper-locations:
    - classpath:mapper/**.xml
  configuration:
    map-underscore-to-camel-case: true